dirs:
  input_pred: /mnt/c/Users/Jannis/Documents/Thesis_Prima/DualTrack/experiment/dualtrack_25/tusrec_25_val/validation_run/scans
  input_gt: /mnt/c/Users/Jannis/Documents/Thesis_Prima/DualTrack/DualTrack_auxiliary/validation_data_tusrec25_converted
  output_dir: /mnt/c/Users/Jannis/Documents/Thesis_Prima/DualTrack/pgo/experiments_2/combined_pgo/2d_ir/dt25_tusrec25_val

general:
  # nr_scans: 1
  # nr_frames: 5
  options: [save_after_each_scan]

pgo:
  options: [noise_constraints]
  ref_values_sigma: 1e-1

linear_approximation:
  profile: tusrec25_dt25
  quantile: 0.9
  scale: 0.8

loop_closure:
  method: nearest_neighbor
  stepsize: 10
  temporal_offset: 50
  threshold: 0.1
  n_neighbors: 4
  loop_consistency_check: false

image_registration:
  ir_type: "2d"
  cross_check: false
  step: 1
  sitk:
    metric: "corr"
    optimizer: "gradient"
    options: [roi, patch_mask, replace_pred]
